In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv("SPO2 - 30-05-2024.txt", delimiter='\t')

In [3]:
df

                  Signal Type: SPO2_Type
0       Start Time: 5/30/2024 8:59:00 PM
1                         Sample Rate: 4
2                         Length: 109398
3                                Unit: %
4                                  Data:
...                                  ...
109398       31.05.2024 04:34:48,250; 96
109399       31.05.2024 04:34:48,500; 97
109400       31.05.2024 04:34:48,750; 97
109401       31.05.2024 04:34:49,000; 97
109402       31.05.2024 04:34:49,250; 97

[109403 rows x 1 columns]

In [4]:
df = df.iloc[5 : , :]

In [6]:
df['Time'] = df['Signal Type: SPO2_Type'].str.split(';').str[0]
df['Value'] = df['Signal Type: SPO2_Type'].str.split(';').str[1]

C:\Users\UTSAV\AppData\Local\Temp\ipykernel_19164\1259655276.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Time'] = df['Signal Type: SPO2_Type'].str.split(';').str[0]
C:\Users\UTSAV\AppData\Local\Temp\ipykernel_19164\1259655276.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Value'] = df['Signal Type: SPO2_Type'].str.split(';').str[1]

In [7]:
df

             Signal Type: SPO2_Type                     Time Value
5       30.05.2024 20:59:00,000; 93  30.05.2024 20:59:00,000    93
6       30.05.2024 20:59:00,250; 94  30.05.2024 20:59:00,250    94
7       30.05.2024 20:59:00,500; 94  30.05.2024 20:59:00,500    94
8       30.05.2024 20:59:00,750; 94  30.05.2024 20:59:00,750    94
9       30.05.2024 20:59:01,000; 94  30.05.2024 20:59:01,000    94
...                             ...                      ...   ...
109398  31.05.2024 04:34:48,250; 96  31.05.2024 04:34:48,250    96
109399  31.05.2024 04:34:48,500; 97  31.05.2024 04:34:48,500    97
109400  31.05.2024 04:34:48,750; 97  31.05.2024 04:34:48,750    97
109401  31.05.2024 04:34:49,000; 97  31.05.2024 04:34:49,000    97
109402  31.05.2024 04:34:49,250; 97  31.05.2024 04:34:49,250    97

[109398 rows x 3 columns]